var package = require('./package.json');

var indentLevel = 4;

var logo = [
    "",
    "╔═══════════╗ ╔════╗ ╔═══════════╗",
    "╚══╗ ╔══════╝ ║ ╔╗ ║ ╚══════╗ ╔══╝",
    "   ║ ║ ╔════╗ ║ ║║ ║ ╔════╗ ║ ║   ",
    "   ║ ║ ║ ╔╗ ║ ║ ╚╝ ║ ║ ╔══╝ ║ ║   ",
    "   ║ ║ ║ ╚╝ ║ ║ ╔╗ ║ ║ ╚══╗ ║ ║   ",
    "   ║ ║ ╚════╝ ║ ║║ ║ ╚══╗ ║ ║ ║   ",
    "   ║ ║ ▐████▌ ║ ║║ ║ ╔══╝ ║ ║ ║   ",
    "   ╚═╝  ▀▀▀▀  ╚═╝╚═╝ ╚════╝ ╚═╝   "
];

var logoStr = logo.join("\n");

function spaces(n) {
    return new Array(n+1).join(" ");
}

function indentArray(str,level) {
    return str.replace(/\n/g, "\n"+spaces(level));
}

function timeStamp() {
    var date = new Date();
    var m = date.getMonth()+1;
    var d = date.getDate();
    var y = date.getFullYear().toString().substr(2);
    var H = date.getHours() % 12;
    H = H === 0 ? 12 : H;
    var M = date.getMinutes();
    M = M < 10 ? "0"+M : M;
    var S = date.getSeconds();
    S = S < 10 ? "0"+S : S;
    var ampm = date.getHours() < 12 ? "am" : "pm";

    return m+"/"+d+"/"+y+", "+H+":"+M+":"+S+" "+ampm;
}

var indent = spaces(indentLevel);

module.exports.print = function(sourceLang,targetLang) {
    var out = "";
    out += indent + "generated by";
    out += indentArray(logoStr,indentLevel) + "\n";
    var version = "version "+package.version;
    var idx = logo[logo.length-1].lastIndexOf("╝") - version.length
                + indentLevel + 1;
    out += spaces(idx) + version + "\n\n";

    out += indent + "generated: " + timeStamp() + "\n";
    out += indent + "source language: " + sourceLang + "\n";
    out += indent + "target language: " + targetLang + "\n";

    out += "";
    return out;
}